import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Provider } from "@/components/ui/provider";
import { Toaster } from "@/components/ui/toaster";
import ThemeProvider from "@/providers/ThemeProvider";
import { StorageProvider } from "@/providers/StorageProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <ThemeProvider>
            <StorageProvider>{children}</StorageProvider>
          </ThemeProvider>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
